#!/usr/bin/env ansible-playbook -i inventory

---

- name: make a docker container with nginx on mac os x
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    web_repo: 'https://github.com/AnsibleDC/AutoDockIT.git'
    web_zip: 'website.zip'

  tasks:

  - name: grab web content from github
    git: repo={{ web_repo }} clone=yes dest=files depth=1

  - name: unarchive the zip content to local files directory
    unarchive:
        src: "files/{{ web_zip }}"
        dest: "{{ playbook_dir }}/files/"

  - name: make a local docker container
    local_action:
      module: docker
      name: nginx
      image: nginx:latest
      expose:
        - 80
      ports:
        - "8880:80"
      volumes:
        - "{{ playbook_dir }}/files:/usr/share/nginx/html:ro"
      tls_hostname: boot2docker
